name: "Mark or close stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-pr-label: "wontfix"
          stale-pr-message: >
            This pr has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          exempt-issue-labels: "type: pinned,type: security"
          exempt-pr-labels: "type: pinned,type: security"

